apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glpi-pvc
  namespace: glpi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard  # เปลี่ยนจาก hostpath เป็น standard
