apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: glpi
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpass
  MYSQL_DATABASE: glpiapiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: glpi
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpass
  MYSQL_DATABASE: glpi
